### ISSUE TITLE
[REVIEW]: Comments on prerelease lang 1.0.0

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-schemas#218]
Here are comments/suggestions on the prerelease:

1.  Can you add a CONTRIBUTORS.md in the lang subdirectory.
2.  Integers is misspelled in `Phonological-Levenshtein-distance-to`.
3.  morpheme misspelled in `Analytic-language-type` description.
4.  Could you clarify the description of `Orthographic-distance-to`?
5.  On the organization of the items under `Relation`:  
    - Maybe you could organize all of these terms under something like `Linguistic-relation`.
    - Is `Phonological-distance-to` necessary as it can't take a value?

We should discuss how to do the distance relationships under `Relation`. The items under `Relation` are of the form (A, (Op, B)). I think having things that take value is okay --- we just hadn't thought of it yet.  It would be helpful to expand the description of these slightly with an example.

Minor editing:  Some descriptions end in period and some do not --- suggest that they all end in period.

**Comment by monique2208** [comment]
Thank you for the review.

I already pushed some fixes to the fork

1. I added the contributors following the same format as on the develop-score branch. 
2. - 3. I fixed the mispelling
4. I changed it to: Removed in orthographic or written form.
5. I have made added a linguistic relation. I was wondering if I should not use Language-relation, because we also have Language-item, and then Language-item property. We do not explicitly use the word linguistic so far. 

Yes, it would be good to discuss the relation with value. For the language schema it always indicated the degree of relatedness. Relatedness itself can also mean a distance (because this is how standardized values are often represented). For orthographic distance, I would imagine something like: Sensory-event, Visual-presentation, (Target, Word, Label/kitten, (Levenshtein-distance-to/3, (Priming, Word, Label/sitting))), for a full event tag. But I was thinking for the description it might make sense to just give an example of the description. So for orthographic distance: for example the word sitting is removed in orthographic or written form from the word kitten (by some measure). What do you think?

I have added periods to all descriptions now.

**Comment by VisLab** [comment]
I think we should allow values in the Relations.  We'll have to make sure there are no issues with validation but I don't think there should be.

**Comment by VisLab** [comment]
PR lang #232 addressed these issues.
