### ISSUE TITLE
[REVIEW]: Prerelease HED SCORE 2.0.0

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-schemas#230]
@dorahermes 
I have been over the schema and think it looks good.  I had the following questions:

1.  I didn't understand why Sensors was under Location-property
2. Spike and Intermittent-photoic-stimulation didn't have descriptions.  I wasn't sure what was the difference between a spike and say a sharp wave.  I also didn't have a good idea how Intermittent was the "Intermittent",
3. Feature-incidence and Feature-prevelance have descriptions that start with the same sentence.  Could you clarify
4. Not sure what is measured for periodic-respiration
5. ECG-normal-rhythm has a # tag, but suggestedTag is Frequency -- maybe it should not have that suggested tag, but its # should have frequencyUnits instead?
6. Myclonus-rhythmic --- the description suggests that its # child should have frequencyUnits.

I'm not clear on what the ordering is of the tags in the schema @IanCa -- what ordering are we applying?

**Comment by VisLab** [comment]
@dorahermes   Could you just look over the comments and respond (you don't have to change anything, but I wanted to make sure that you looked at these before release).  Thx

**Comment by dorahermes** [comment]
> 1. I didn't understand why Sensors was under Location-property

Sensors always measure from a certain location. Could be one level up if preferred.

> 2. Spike and Intermittent-photoic-stimulation didn't have descriptions.  I wasn't sure what was the difference between a spike and say a sharp wave.  I also didn't have a good idea how Intermittent was the "Intermittent",

Not sure what I missed, as Spike has a definition: "A transient, clearly distinguished from background activity, with pointed peak at a conventional paper speed or time scale and duration from 20 to under 70 ms, i.e. 1/50-1/15 s approximately. Main component is generally negative relative to other areas. Amplitude varies. (Source: Beniczky ea 2017, Table 5; Beniczky ea 2013, Appendix S4.)"
Intermittent photic stimulation is typically applied with many different frequencies to test patients sensitivity, which is why it has a numericClass and frequencyUnits attached. 

> 3. Feature-incidence and Feature-prevelance have descriptions that start with the same sentence.  Could you clarify

Clarified:
** Feature-incidence <nowiki>[For single discharges, estimates of how often features are seen in the recording are scored as incidence (how often it occurs/time-epoch). (Source: Beniczky ea 2017, Section 8, Table 6.)]</nowiki>
** Feature-prevalence <nowiki>[For trains or bursts, estimates of how often features are seen in the recording are scored as prevalence (the percentage of the recording covered by the train/burst). (Source: Beniczky ea 2017, Section 8, Table 6, Table 8.)]</nowiki>

> 4. Not sure what is measured for periodic-respiration

This is a clinical term, there is a wikipedia definition if that's recommended in HED?

> 5. ECG-normal-rhythm has a # tag, but suggestedTag is Frequency -- maybe it should not have that suggested tag, but its # should have frequencyUnits instead?

Removed child, left suggested tag (per paper). We should discuss, also perhaps issue for bradycardia.

> 6. Myclonus-rhythmic --- the description suggests that its # child should have frequencyUnits.

Added frequencyUnits
 
> 7. I'm not clear on what the ordering is of the tags in the schema @IanCa -- what ordering are we applying?

Would be good to know the guideline, thanks!

**Comment by VisLab** [comment]
@dorahermes - thanks for your response --- I will do a PR to make the changes as we had to change our branch rules and we don't have a writeup about them yet. 

On 1.) I'll move up since this is applicable to more features.
On 2.) No clue what I was looking at. Sorry...
On 3.) I'll add your comments.
On 4.) I'll put in the Wikipedia definitions.
On 5.) After looking at it again -- I'm going to keep the suggestedTag and keep the child text description and do the same thing for bradycardia.  This allows notes. 
on 6.  I'll add the units.

I'll do a PR and ask for your review -- anything you don't agree with we can change during the review.  I think it is pretty close.
