### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by monique2208** [hed-standard/hed-schemas#53]
There is typo in the schema: Gentalia -> Genitalia

**Comment by VisLab** [comment]
Bummer.... I guess it was inevitable that some node name would be misspelled.

We will need to address the issue of tag deprecation concretely sooner rather than later. 
We don't want to have both versions side-by-side in the schema as this would be disturbing for users.

One possibility is that deprecated tag nodes would be moved to a special deprecated section.
We could introduce a `Replace-by` attribute that would  indicate what the deprecated tag should be replaced by in the future.
For simple replacement (one-for-one), this would be simple and could be done in a preprocessing step by tools.
We might also want to introduce a `History` attribute.

More complicated replacement rules might be introduced in the future, but I don't think we should rush into that.

Comments?  @dungscout96 @IanCa @smakeig @happy5214
